### ISSUE TITLE
Suggestion: allow answers not in match

### ISSUE THREAD

**Issue by Thesola10** [andreax79/pzp#3]
This would be useful for open-ended prompts, where an answer that isn't in the initial suggestion set can be entered.

That, or adding a secondary selection set which is only shown when you start typing or run out of matches, to emphasize the semantic difference between suggested and possible choices

**Comment by andreax79** [comment]
Great idea! I've included the user input as a line attribute for Exceptions in the new version (0.0.20).
Please review the number_selector example.

While the second option is interesting, it appears a bit more complicated, and I need to ponder it further.

**Comment by Thesola10** [comment]
Thank you so much! On an unrelated note, is it possible to hide the number of suggestions in a layout? (the yellow `2/2`)

**Comment by andreax79** [comment]
Yes, you can use  `Finder(info_style=InfoStyle.HIDDEN)` in order to hide the numbers.
