### ISSUE TITLE
info_style = InfoStyle.HIDDEN causes graphical glitch with reverse layout

### ISSUE THREAD

**Issue by Thesola10** [andreax79/pzp#4]
If I show a Picker with `info_style = InfoStyle.HIDDEN, fullscreen = False, layout = 'reverse'`, selecting or typing an option causes the entire widget to be redrawn one line above its original place, eventually overwriting my terminal history.

Footage:

[Capture vidéo du 2023-03-01 10-28-35.webm](https://user-images.githubusercontent.com/7287268/222098683-7af8cedc-c7eb-432f-8bab-9c7bee94a7af.webm)

**Comment by andreax79** [comment]
Fixed in the new version 0.0.22, please check if it work correctly now.

**Comment by Thesola10** [comment]
thanks!
